09-01-ReactiveLosing
js-tasks-ru/vue-20221107_aliya pull request #13
Opened 2023-01-04 14:24 UTC by mar1704

2023-01-04 14:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-01-08 13:40 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-10 22:33 UTC, ShGKme requested changes
Попробуйте найти прчину потери реактивность и исправить её в первой задаче.

2023-01-10 22:33 UTC, ShGKme commented on 08-reactivity/01-reactivity-losing/components/SensorsDataView.vue
>    },
Такое решение в итоге визуально почти работает, но не решает в полной мере проблему реактивности. Метод `getData()` ничего не возвращает. В итоге раз в секунду здесь вызывается `setData(undefined)`. Через какое-то время данные обновляются и автоматически вызывается как коллбек `setData` уже с полученными данными. Из-за постоянного переприсваивания данных через `undefined` в итоге страница обновляется. Но из-за этого она мелкает блоком "Loading..." каждый раз, когда обновляются данные. 

Попробуйте найти причину потери реактивности и исправить её так, чтобы страница обновляла только числа, не переходя снова в состояние "Loading...".

2023-01-10 22:33 UTC, ShGKme commented on 08-reactivity/02-scroll-after-update/components/MiniMessenger.vue
> +  }  ,
Решение с nextTick верное, но лучше это делать не в отслеживании ввода нового сообщения, а при его отправке. Иначе скрооллинг срабатывает при вводе каждой буквы ещё до появления нового сообщения в списке.

2023-01-13 15:32 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-13 18:04 UTC, ShGKme commented
Нужна ли помощь с `08-reactivity/01-reactivity-losing`?

2023-01-13 19:17 UTC, mar1704 commented
> 

Спасибо, но я посмотрела решение преподавателя. Изначально я поняла, что проблема в том, что напрямую меняем оригинальный объект и в этом причина потеря реактивности, но что именно не так и как исправить не поняла, поэтому посмотрела решение, все понятно теперь

2023-01-13 22:47 UTC, ShGKme approved these changes
Принято

2023-01-13 22:47 UTC, merged