03-MarkedList
js-tasks-ru/vue-20221107_aliya pull request #4
Opened 2022-11-15 05:56 UTC by mar1704

Не поняла, как решить задачу как написано в примечании задачи:
"через новый массив, содержащий в каждом элементе как Email, так и флаг его выделения". 
Не стала выносить условие для класса в компонент, тк в нем завязка на конкретные  email:
 <li v-for="email in newEmails" :class="{marked: filterEmails.includes(email)}" >

2022-11-15 05:56 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-11-16 21:53 UTC, ShGKme requested changes
В текущем решении вычисляемое свойство не помогает выводить почты, а напротив, даже усложняет и замедляет вывод. Требуется подумать, как сделать такое вычисляемое свойство, которое помогает решать задачу вывода маркированных почт.

2022-11-16 21:53 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
На вебинаре мы использовали вычисляемое свойство для подготовки **отфильтрованных** данных, но здесь - другая задача. Здесь требуется вывести **ВСЕ** данные, но некоторые элементы - **отметить** маркировкой.

В вычисляемом свойстве нужно вернуть что-то, что поможет вывести список с не только самой почтой, но и классом с маркировкой при необхоидмости.

Для этого можно на основе исходного массива строк с почтами вернуть новый массив, где каждый элемент - объект. В объект уже можно положить как исходную почту, так и флаг о маркировке (вычислять также, как сейчас делаете проверку в фильтре). Альтернативное решение - вычислить что-то дополнительное, что позволит быстро по почте при выводе узнать, нужно ли её маркировать.

2022-11-16 21:53 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Также вызывает вопросы свойство `this.filterArr`. Какая роль этого свойства, кроме как в хранении пустого массива?

2022-11-16 21:53 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +      </template>
Лучше избегать вызова методов в шаблоне.

1. Требуется чуть больше думать, смотря на шаблон, чтобы понять, что эти методы не имеют побочных эффектов или проблем с производительностью.
2. Шаблон получается менее декларативным, так как уже не декларирует значение атрибута/содержимого, а вычисляет в процессе работы.

2022-11-16 21:53 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +      </template>
В текущем решении для вывода списка идёт перебор всех почт, а также заранее вычисляется отфильтрованный список. При вычислении отфильтрованного списка уже для каждой почты проверяется, подходит она, или нет.

При выводе для каждой почты происходит ещё один перебор уже отфильтрованного списка, чтобы проверить, не попадает ли почта в список ранее вычисленного отфильтрованного, где её уже проверили.

Так при каждом рендеринге, даже если новый рендеринг не был связан с изменением поиска или списка почт. Получается не очень оптимально, и даже менее оптимально, чем при решении без вычисляемого свойства вообще, с проверкой почты прямо при выводе.

2022-11-16 21:53 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +      </template>
Элемент `<template>` в шаблоне нужен, когда требуется для директив `v-if` или `v-for` обернуть несколько узлов сразу.

Если узел один, то директиву можно использовать непосредственно на нём без лишних обёрток.

2022-11-16 21:55 UTC, ShGKme commented
> Не поняла, как решить задачу как написано в примечании задачи:
> "через новый массив, содержащий в каждом элементе как Email, так и флаг его выделения".
> Не стала выносить условие для класса в компонент, тк в нем завязка на конкретные email:

Ответил в комментариях к текущему решению. Если комментарии не помогли - пишите, будем разбирать подробнее :)

2022-11-20 10:55 UTC, closed without merging

2022-11-20 10:55 UTC, mar1704 commented
закрываю PR , тк посмотрела решение преподавателя на странице задачи